export const plans = [
  {
    planId: "free",
    name: "Free Plan",
    subtitle: "Perfect for getting started with B2B sales",
    price: 0,
    period: "month",
    maxCatalogs: 1,
    maxCompanies: 5,
    maxOrders: 50,
    features: [
      "1 Catalog",
      "5 Companies",
      "50 Orders per month",
      "Basic B2B features",
      "Company customer management",
      "Basic order tracking"
    ],
    popular: false,
    highlighted: false,
  },
  {
    planId: "basic",
    name: "Basic Plan",
    subtitle: "Ideal for growing B2B businesses",
    price: 29.99,
    period: "month",
    badge: "Most Popular",
    maxCatalogs: 5,
    maxCompanies: 20,
    maxOrders: 200,
    features: [
      "5 Catalogs",
      "20 Companies",
      "200 Orders per month",
      "Price list management",
      "Company location support",
      "Advanced catalog features",
      "Email support",
    ],
    popular: true,
    highlighted: true,
  },
  {
    planId: "pro",
    name: "Pro Plan", 
    subtitle: "For enterprise-level B2B operations",
    price: 79.99,
    period: "month",
    maxCatalogs: 999,
    maxCompanies: 999,
    maxOrders: 999999,
    features: [
      "Unlimited Catalogs",
      "Unlimited Companies",
      "Unlimited Orders",
      "Advanced B2B features",
      "Custom pricing rules",
      "Publication management",
      "Advanced reporting",
      "Priority support",
    ],
    popular: false,
    highlighted: false,
  },
];